# Generated by Django 5.2.12 on 2026-04-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='The Critic', max_length=200)),
                ('email', models.EmailField(help_text='Main contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address_line1', models.CharField(blank=True, help_text='First line of address', max_length=200)),
                ('address_line2', models.CharField(blank=True, help_text='Second line of address', max_length=200)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('editorial_email', models.EmailField(blank=True, help_text='Editorial department email', max_length=254)),
                ('advertising_email', models.EmailField(blank=True, help_text='Advertising department email', max_length=254)),
                ('support_email', models.EmailField(blank=True, help_text='Technical support email', max_length=254)),
                ('general_email', models.EmailField(blank=True, help_text='General inquiries email', max_length=254)),
                ('business_hours', models.CharField(default='Mon - Fri, 9:00 AM - 6:00 PM GMT', help_text='Business hours', max_length=100)),
                ('twitter_link', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('linkedin_link', models.URLField(blank=True, help_text='LinkedIn company page URL')),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook page URL')),
                ('contact_form_message', models.TextField(blank=True, help_text='Message displayed above contact form')),
                ('location_description', models.TextField(blank=True, help_text='Description of office location')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this contact info is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
