# Generated by Django 6.0 on 2026-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
