# Generated by Django 5.2.12 on 2026-04-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_customer_reset_token_customer_reset_token_expires'),
        ('core_api', '0004_demobooking_scheduled_date_and_more'),
    ]

    operations = [
    ]
