# Generated by Django 5.2.12 on 2026-09-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_merge_20260430_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reset_token_expires',
        ),
        migrations.AddField(
            model_name='customer',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
