# Generated by Django 5.2.12 on 2026-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_customer_auth_provider_customer_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
